/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`rate_limits_endpoint_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RateLimitsEndpointIdDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rate_limits_endpoint_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RateLimitsEndpointIdGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rate_limits_endpoint_id_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RateLimitsEndpointIdPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`rate_limits_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RateLimitsGetError {
    UnknownValue(serde_json::Value),
}


pub async fn rate_limits_endpoint_id_delete(configuration: &configuration::Configuration, endpoint_id: &str) -> Result<(), Error<RateLimitsEndpointIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;

    let uri_str = format!("{}/rate-limits/{endpoint_id}", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RateLimitsEndpointIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn rate_limits_endpoint_id_get(configuration: &configuration::Configuration, endpoint_id: &str) -> Result<(), Error<RateLimitsEndpointIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;

    let uri_str = format!("{}/rate-limits/{endpoint_id}", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RateLimitsEndpointIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn rate_limits_endpoint_id_post(configuration: &configuration::Configuration, endpoint_id: &str) -> Result<(), Error<RateLimitsEndpointIdPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;

    let uri_str = format!("{}/rate-limits/{endpoint_id}", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RateLimitsEndpointIdPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn rate_limits_get(configuration: &configuration::Configuration, ) -> Result<(), Error<RateLimitsGetError>> {

    let uri_str = format!("{}/rate-limits", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RateLimitsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

