/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`endpoints_endpoint_id_transforms_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EndpointsEndpointIdTransformsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`endpoints_endpoint_id_transforms_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EndpointsEndpointIdTransformsIdDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`endpoints_endpoint_id_transforms_id_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EndpointsEndpointIdTransformsIdPutError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`endpoints_endpoint_id_transforms_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EndpointsEndpointIdTransformsPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`endpoints_endpoint_id_transforms_test_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EndpointsEndpointIdTransformsTestPostError {
    UnknownValue(serde_json::Value),
}


pub async fn endpoints_endpoint_id_transforms_get(configuration: &configuration::Configuration, endpoint_id: &str) -> Result<Vec<models::TransformRule>, Error<EndpointsEndpointIdTransformsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;

    let uri_str = format!("{}/endpoints/{endpoint_id}/transforms", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::TransformRule&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::TransformRule&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EndpointsEndpointIdTransformsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn endpoints_endpoint_id_transforms_id_delete(configuration: &configuration::Configuration, endpoint_id: &str, id: &str) -> Result<(), Error<EndpointsEndpointIdTransformsIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;
    let p_path_id = id;

    let uri_str = format!("{}/endpoints/{endpoint_id}/transforms/{id}", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id), id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<EndpointsEndpointIdTransformsIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn endpoints_endpoint_id_transforms_id_put(configuration: &configuration::Configuration, endpoint_id: &str, id: &str, body: serde_json::Value) -> Result<models::TransformRule, Error<EndpointsEndpointIdTransformsIdPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;
    let p_path_id = id;
    let p_body_body = body;

    let uri_str = format!("{}/endpoints/{endpoint_id}/transforms/{id}", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id), id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TransformRule`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TransformRule`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EndpointsEndpointIdTransformsIdPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn endpoints_endpoint_id_transforms_post(configuration: &configuration::Configuration, endpoint_id: &str, create_transform_rule_request: models::CreateTransformRuleRequest) -> Result<models::TransformRule, Error<EndpointsEndpointIdTransformsPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;
    let p_body_create_transform_rule_request = create_transform_rule_request;

    let uri_str = format!("{}/endpoints/{endpoint_id}/transforms", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_transform_rule_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TransformRule`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TransformRule`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EndpointsEndpointIdTransformsPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn endpoints_endpoint_id_transforms_test_post(configuration: &configuration::Configuration, endpoint_id: &str, endpoints_endpoint_id_transforms_test_post_request: models::EndpointsEndpointIdTransformsTestPostRequest) -> Result<(), Error<EndpointsEndpointIdTransformsTestPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_endpoint_id = endpoint_id;
    let p_body_endpoints_endpoint_id_transforms_test_post_request = endpoints_endpoint_id_transforms_test_post_request;

    let uri_str = format!("{}/endpoints/{endpoint_id}/transforms/test", configuration.base_path, endpoint_id=crate::apis::urlencode(p_path_endpoint_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_endpoints_endpoint_id_transforms_test_post_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<EndpointsEndpointIdTransformsTestPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

