/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminUsersIdPlanPutRequest {
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<Plan>,
}

impl AdminUsersIdPlanPutRequest {
    pub fn new() -> AdminUsersIdPlanPutRequest {
        AdminUsersIdPlanPutRequest {
            plan: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Plan {
    #[serde(rename = "free")]
    Free,
    #[serde(rename = "pro")]
    Pro,
    #[serde(rename = "business")]
    Business,
}

impl Default for Plan {
    fn default() -> Plan {
        Self::Free
    }
}

