/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminUsersIdGet200Response {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserSummary>>,
    #[serde(rename = "endpoints", skip_serializing_if = "Option::is_none")]
    pub endpoints: Option<Vec<models::AdminUsersIdGet200ResponseEndpointsInner>>,
    #[serde(rename = "recent_deliveries", skip_serializing_if = "Option::is_none")]
    pub recent_deliveries: Option<Vec<models::AdminUsersIdGet200ResponseRecentDeliveriesInner>>,
    #[serde(rename = "usage_stats", skip_serializing_if = "Option::is_none")]
    pub usage_stats: Option<Box<models::AdminUsersIdGet200ResponseUsageStats>>,
}

impl AdminUsersIdGet200Response {
    pub fn new() -> AdminUsersIdGet200Response {
        AdminUsersIdGet200Response {
            user: None,
            endpoints: None,
            recent_deliveries: None,
            usage_stats: None,
        }
    }
}

