/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminUsersIdGet200ResponseUsageStats {
    #[serde(rename = "total_deliveries", skip_serializing_if = "Option::is_none")]
    pub total_deliveries: Option<i32>,
    #[serde(rename = "success_rate", skip_serializing_if = "Option::is_none")]
    pub success_rate: Option<f64>,
    #[serde(rename = "endpoints_count", skip_serializing_if = "Option::is_none")]
    pub endpoints_count: Option<i32>,
}

impl AdminUsersIdGet200ResponseUsageStats {
    pub fn new() -> AdminUsersIdGet200ResponseUsageStats {
        AdminUsersIdGet200ResponseUsageStats {
            total_deliveries: None,
            success_rate: None,
            endpoints_count: None,
        }
    }
}

