/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminFeatureFlagsPostRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    #[serde(rename = "rollout_percentage", skip_serializing_if = "Option::is_none")]
    pub rollout_percentage: Option<i32>,
    #[serde(rename = "enabled_for_plans", skip_serializing_if = "Option::is_none")]
    pub enabled_for_plans: Option<Vec<String>>,
}

impl AdminFeatureFlagsPostRequest {
    pub fn new(name: String) -> AdminFeatureFlagsPostRequest {
        AdminFeatureFlagsPostRequest {
            name,
            description: None,
            is_enabled: None,
            rollout_percentage: None,
            enabled_for_plans: None,
        }
    }
}

