/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthConsentPostRequest {
    /// Consent key (e.g. cookie_consent, marketing_consent)
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: bool,
}

impl AuthConsentPostRequest {
    pub fn new(key: String, value: bool) -> AuthConsentPostRequest {
        AuthConsentPostRequest {
            key,
            value,
        }
    }
}

