/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Auth2faEnablePost200Response {
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    #[serde(rename = "qr_url", skip_serializing_if = "Option::is_none")]
    pub qr_url: Option<String>,
}

impl Auth2faEnablePost200Response {
    pub fn new() -> Auth2faEnablePost200Response {
        Auth2faEnablePost200Response {
            secret: None,
            qr_url: None,
        }
    }
}

