/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthLoginPost200Response {
    AuthResponse(Box<models::AuthResponse>),
    TwoFactorRequiredResponse(Box<models::TwoFactorRequiredResponse>),
}

impl Default for AuthLoginPost200Response {
    fn default() -> Self {
        Self::AuthResponse(Default::default())
    }
}

