/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthConsentGet200Response {
    #[serde(rename = "consents", skip_serializing_if = "Option::is_none")]
    pub consents: Option<std::collections::HashMap<String, bool>>,
}

impl AuthConsentGet200Response {
    pub fn new() -> AuthConsentGet200Response {
        AuthConsentGet200Response {
            consents: None,
        }
    }
}

