/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointsEndpointIdTransformsTestPostRequest {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    #[serde(rename = "rule_id", skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<uuid::Uuid>,
}

impl EndpointsEndpointIdTransformsTestPostRequest {
    pub fn new() -> EndpointsEndpointIdTransformsTestPostRequest {
        EndpointsEndpointIdTransformsTestPostRequest {
            payload: None,
            rule_id: None,
        }
    }
}

