/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboundConfigsPostRequest {
    /// Provider name (stripe, github, shopify, generic)
    #[serde(rename = "provider")]
    pub provider: String,
    /// Webhook signing secret
    #[serde(rename = "secret")]
    pub secret: String,
    /// Default target endpoint
    #[serde(rename = "endpoint_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub endpoint_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

impl InboundConfigsPostRequest {
    pub fn new(provider: String, secret: String) -> InboundConfigsPostRequest {
        InboundConfigsPostRequest {
            provider,
            secret,
            endpoint_id: None,
            enabled: None,
        }
    }
}

