/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaygroundGet200Response {
    #[serde(rename = "endpoints", skip_serializing_if = "Option::is_none")]
    pub endpoints: Option<Vec<serde_json::Value>>,
    #[serde(rename = "sample_payloads", skip_serializing_if = "Option::is_none")]
    pub sample_payloads: Option<Vec<serde_json::Value>>,
}

impl PlaygroundGet200Response {
    pub fn new() -> PlaygroundGet200Response {
        PlaygroundGet200Response {
            endpoints: None,
            sample_payloads: None,
        }
    }
}

