/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortalNotificationsPut200Response {
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<bool>,
    #[serde(rename = "preferences", skip_serializing_if = "Option::is_none")]
    pub preferences: Option<Box<models::NotificationPreferences>>,
}

impl PortalNotificationsPut200Response {
    pub fn new() -> PortalNotificationsPut200Response {
        PortalNotificationsPut200Response {
            updated: None,
            preferences: None,
        }
    }
}

