/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminRevenueEntry : Monthly revenue data point
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminRevenueEntry {
    #[serde(rename = "date")]
    pub date: chrono::NaiveDate,
    /// Monthly recurring revenue in dollars
    #[serde(rename = "mrr")]
    pub mrr: f64,
    #[serde(rename = "new_subscriptions")]
    pub new_subscriptions: i32,
    #[serde(rename = "churns")]
    pub churns: i32,
}

impl AdminRevenueEntry {
    /// Monthly revenue data point
    pub fn new(date: chrono::NaiveDate, mrr: f64, new_subscriptions: i32, churns: i32) -> AdminRevenueEntry {
        AdminRevenueEntry {
            date,
            mrr,
            new_subscriptions,
            churns,
        }
    }
}

