/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminAuditEntry : A single admin audit log entry
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminAuditEntry {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "resource_type")]
    pub resource_type: String,
    #[serde(rename = "resource_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resource_id: Option<Option<String>>,
    #[serde(rename = "details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details: Option<Option<serde_json::Value>>,
    #[serde(rename = "ip_address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<Option<String>>,
    #[serde(rename = "user_agent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl AdminAuditEntry {
    /// A single admin audit log entry
    pub fn new(id: uuid::Uuid, customer_id: uuid::Uuid, action: String, resource_type: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> AdminAuditEntry {
        AdminAuditEntry {
            id,
            customer_id,
            action,
            resource_type,
            resource_id: None,
            details: None,
            ip_address: None,
            user_agent: None,
            created_at,
        }
    }
}

