/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminRevenueResponse : Revenue history for admin analytics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminRevenueResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::AdminRevenueEntry>,
    /// Current total MRR across all subscriptions
    #[serde(rename = "total_mrr")]
    pub total_mrr: f64,
}

impl AdminRevenueResponse {
    /// Revenue history for admin analytics
    pub fn new(data: Vec<models::AdminRevenueEntry>, total_mrr: f64) -> AdminRevenueResponse {
        AdminRevenueResponse {
            data,
            total_mrr,
        }
    }
}

