/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminAuditLogResponse : Paginated admin audit log response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminAuditLogResponse {
    #[serde(rename = "entries")]
    pub entries: Vec<models::AdminAuditEntry>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "per_page")]
    pub per_page: i32,
}

impl AdminAuditLogResponse {
    /// Paginated admin audit log response
    pub fn new(entries: Vec<models::AdminAuditEntry>, total: i32, page: i32, per_page: i32) -> AdminAuditLogResponse {
        AdminAuditLogResponse {
            entries,
            total,
            page,
            per_page,
        }
    }
}

