/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminAlertRule : Admin alert rule with customer info
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminAlertRule {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "customer_id", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<uuid::Uuid>,
    #[serde(rename = "customer_email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_email: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "condition")]
    pub condition: Condition,
    #[serde(rename = "threshold")]
    pub threshold: i32,
    #[serde(rename = "channels")]
    pub channels: Vec<Channels>,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl AdminAlertRule {
    /// Admin alert rule with customer info
    pub fn new(id: uuid::Uuid, name: String, condition: Condition, threshold: i32, channels: Vec<Channels>, is_active: bool, created_at: chrono::DateTime<chrono::FixedOffset>) -> AdminAlertRule {
        AdminAlertRule {
            id,
            customer_id: None,
            customer_email: None,
            name,
            condition,
            threshold,
            channels,
            is_active,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Condition {
    #[serde(rename = "failure_rate")]
    FailureRate,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "consecutive_failures")]
    ConsecutiveFailures,
}

impl Default for Condition {
    fn default() -> Condition {
        Self::FailureRate
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Channels {
    #[serde(rename = "slack")]
    Slack,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "webhook")]
    Webhook,
}

impl Default for Channels {
    fn default() -> Channels {
        Self::Slack
    }
}

