/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminTestWebhookResponse : Result of a test webhook delivery
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminTestWebhookResponse {
    #[serde(rename = "status_code")]
    pub status_code: i32,
    #[serde(rename = "response_body")]
    pub response_body: String,
    #[serde(rename = "duration_ms")]
    pub duration_ms: i32,
}

impl AdminTestWebhookResponse {
    /// Result of a test webhook delivery
    pub fn new(status_code: i32, response_body: String, duration_ms: i32) -> AdminTestWebhookResponse {
        AdminTestWebhookResponse {
            status_code,
            response_body,
            duration_ms,
        }
    }
}

