/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdminSystemStatus : System-level status for admin dashboard
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminSystemStatus {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "uptime_seconds")]
    pub uptime_seconds: i32,
    #[serde(rename = "db_status")]
    pub db_status: DbStatus,
    #[serde(rename = "redis_status")]
    pub redis_status: RedisStatus,
    /// Number of pending jobs in the delivery queue
    #[serde(rename = "queue_depth")]
    pub queue_depth: i32,
}

impl AdminSystemStatus {
    /// System-level status for admin dashboard
    pub fn new(version: String, uptime_seconds: i32, db_status: DbStatus, redis_status: RedisStatus, queue_depth: i32) -> AdminSystemStatus {
        AdminSystemStatus {
            version,
            uptime_seconds,
            db_status,
            redis_status,
            queue_depth,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DbStatus {
    #[serde(rename = "healthy")]
    Healthy,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "down")]
    Down,
}

impl Default for DbStatus {
    fn default() -> DbStatus {
        Self::Healthy
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RedisStatus {
    #[serde(rename = "healthy")]
    Healthy,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "down")]
    Down,
}

impl Default for RedisStatus {
    fn default() -> RedisStatus {
        Self::Healthy
    }
}

