/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AlertRuleListResponse : Paginated list of alert rules
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertRuleListResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::AlertRule>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "total")]
    pub total: i32,
}

impl AlertRuleListResponse {
    /// Paginated list of alert rules
    pub fn new(data: Vec<models::AlertRule>, has_more: bool, total: i32) -> AlertRuleListResponse {
        AlertRuleListResponse {
            data,
            has_more,
            total,
        }
    }
}

