/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnalyticsTrendResponse : Delivery trend data over a time period
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsTrendResponse {
    /// Array of trend data points
    #[serde(rename = "data")]
    pub data: Vec<models::AnalyticsTrendPoint>,
    /// Time range of the data
    #[serde(rename = "period")]
    pub period: Period,
}

impl AnalyticsTrendResponse {
    /// Delivery trend data over a time period
    pub fn new(data: Vec<models::AnalyticsTrendPoint>, period: Period) -> AnalyticsTrendResponse {
        AnalyticsTrendResponse {
            data,
            period,
        }
    }
}
/// Time range of the data
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Period {
    #[serde(rename = "24h")]
    Variant24h,
    #[serde(rename = "7d")]
    Variant7d,
    #[serde(rename = "30d")]
    Variant30d,
}

impl Default for Period {
    fn default() -> Period {
        Self::Variant24h
    }
}

