/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnalyticsTrendPoint : Single data point in a delivery trend
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsTrendPoint {
    /// Date of the data point
    #[serde(rename = "date")]
    pub date: chrono::NaiveDate,
    /// Total deliveries on this date
    #[serde(rename = "total")]
    pub total: i32,
    /// Successfully delivered on this date
    #[serde(rename = "successful")]
    pub successful: i32,
    /// Failed deliveries on this date
    #[serde(rename = "failed")]
    pub failed: i32,
    /// Average delivery latency in milliseconds
    #[serde(rename = "avg_latency_ms", skip_serializing_if = "Option::is_none")]
    pub avg_latency_ms: Option<f32>,
}

impl AnalyticsTrendPoint {
    /// Single data point in a delivery trend
    pub fn new(date: chrono::NaiveDate, total: i32, successful: i32, failed: i32) -> AnalyticsTrendPoint {
        AnalyticsTrendPoint {
            date,
            total,
            successful,
            failed,
            avg_latency_ms: None,
        }
    }
}

