/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyInfo {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Masked key prefix (e.g. \"hs_abc1...\")
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "last_used_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<Option<String>>,
    #[serde(rename = "is_active")]
    pub is_active: bool,
}

impl ApiKeyInfo {
    pub fn new(id: uuid::Uuid, prefix: String, created_at: chrono::DateTime<chrono::FixedOffset>, is_active: bool) -> ApiKeyInfo {
        ApiKeyInfo {
            id,
            prefix,
            created_at,
            last_used_at: None,
            is_active,
        }
    }
}

