/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuditLogEntry : A single audit log record
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogEntry {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Who performed the action (user id or email)
    #[serde(rename = "actor")]
    pub actor: String,
    /// The action taken (e.g. endpoint.create, team.invite)
    #[serde(rename = "action")]
    pub action: String,
    /// Type of resource affected (endpoint, team, api_key, etc.)
    #[serde(rename = "resource_type")]
    pub resource_type: String,
    /// ID of the affected resource
    #[serde(rename = "resource_id")]
    pub resource_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
    /// Additional context (old_value, new_value, ip, etc.)
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<serde_json::Value>>,
}

impl AuditLogEntry {
    /// A single audit log record
    pub fn new(id: uuid::Uuid, actor: String, action: String, resource_type: String, resource_id: String, timestamp: chrono::DateTime<chrono::FixedOffset>) -> AuditLogEntry {
        AuditLogEntry {
            id,
            actor,
            action,
            resource_type,
            resource_id,
            timestamp,
            metadata: None,
        }
    }
}

