/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuditLogListResponse : Paginated list of audit log entries
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogListResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::AuditLogEntry>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "total")]
    pub total: i32,
}

impl AuditLogListResponse {
    /// Paginated list of audit log entries
    pub fn new(data: Vec<models::AuditLogEntry>, has_more: bool, total: i32) -> AuditLogListResponse {
        AuditLogListResponse {
            data,
            has_more,
            total,
        }
    }
}

