/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchWebhookResponse : Response for batch webhook delivery creation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchWebhookResponse {
    /// List of created delivery IDs
    #[serde(rename = "delivery_ids")]
    pub delivery_ids: Vec<uuid::Uuid>,
    /// Number of deliveries created
    #[serde(rename = "count")]
    pub count: i32,
}

impl BatchWebhookResponse {
    /// Response for batch webhook delivery creation
    pub fn new(delivery_ids: Vec<uuid::Uuid>, count: i32) -> BatchWebhookResponse {
        BatchWebhookResponse {
            delivery_ids,
            count,
        }
    }
}

