/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchResponse {
    #[serde(rename = "deliveries")]
    pub deliveries: Vec<models::Delivery>,
    #[serde(rename = "errors")]
    pub errors: Vec<models::BatchResponseErrorsInner>,
}

impl BatchResponse {
    pub fn new(deliveries: Vec<models::Delivery>, errors: Vec<models::BatchResponseErrorsInner>) -> BatchResponse {
        BatchResponse {
            deliveries,
            errors,
        }
    }
}

