/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BillingPortalResponse : URL for the customer billing portal
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingPortalResponse {
    /// Stripe billing portal URL
    #[serde(rename = "url")]
    pub url: String,
}

impl BillingPortalResponse {
    /// URL for the customer billing portal
    pub fn new(url: String) -> BillingPortalResponse {
        BillingPortalResponse {
            url,
        }
    }
}

