/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CancelSubscriptionResponse : Result of subscription cancellation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelSubscriptionResponse {
    #[serde(rename = "cancelled_at")]
    pub cancelled_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "ends_at")]
    pub ends_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CancelSubscriptionResponse {
    /// Result of subscription cancellation
    pub fn new(cancelled_at: chrono::DateTime<chrono::FixedOffset>, ends_at: chrono::DateTime<chrono::FixedOffset>) -> CancelSubscriptionResponse {
        CancelSubscriptionResponse {
            cancelled_at,
            ends_at,
        }
    }
}

