/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CancelSubscriptionRequest : Request to cancel current subscription
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelSubscriptionRequest {
    /// Optional reason for cancellation
    #[serde(rename = "reason")]
    pub reason: String,
}

impl CancelSubscriptionRequest {
    /// Request to cancel current subscription
    pub fn new(reason: String) -> CancelSubscriptionRequest {
        CancelSubscriptionRequest {
            reason,
        }
    }
}

