/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePasswordRequest {
    #[serde(rename = "current_password")]
    pub current_password: String,
    #[serde(rename = "new_password")]
    pub new_password: String,
}

impl ChangePasswordRequest {
    pub fn new(current_password: String, new_password: String) -> ChangePasswordRequest {
        ChangePasswordRequest {
            current_password,
            new_password,
        }
    }
}

