/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChurnedUser : A user who churned (became inactive) recently
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChurnedUser {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "churn_date")]
    pub churn_date: chrono::DateTime<chrono::FixedOffset>,
}

impl ChurnedUser {
    /// A user who churned (became inactive) recently
    pub fn new(id: uuid::Uuid, email: String, plan: String, amount: f64, churn_date: chrono::DateTime<chrono::FixedOffset>) -> ChurnedUser {
        ChurnedUser {
            id,
            email,
            name: None,
            plan,
            amount,
            churn_date,
        }
    }
}

