/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChurnResponse : Churn report with list of recently churned users
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChurnResponse {
    #[serde(rename = "users")]
    pub users: Vec<models::ChurnedUser>,
}

impl ChurnResponse {
    /// Churn report with list of recently churned users
    pub fn new(users: Vec<models::ChurnedUser>) -> ChurnResponse {
        ChurnResponse {
            users,
        }
    }
}

