/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAlertRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "condition")]
    pub condition: Condition,
    #[serde(rename = "threshold")]
    pub threshold: i32,
    #[serde(rename = "channels")]
    pub channels: Vec<String>,
    #[serde(rename = "endpoint_id", skip_serializing_if = "Option::is_none")]
    pub endpoint_id: Option<uuid::Uuid>,
}

impl CreateAlertRequest {
    pub fn new(name: String, condition: Condition, threshold: i32, channels: Vec<String>) -> CreateAlertRequest {
        CreateAlertRequest {
            name,
            condition,
            threshold,
            channels,
            endpoint_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Condition {
    #[serde(rename = "failure_rate")]
    FailureRate,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "consecutive_failures")]
    ConsecutiveFailures,
}

impl Default for Condition {
    fn default() -> Condition {
        Self::FailureRate
    }
}

