/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTransformRuleRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "rule_type")]
    pub rule_type: String,
    #[serde(rename = "config")]
    pub config: serde_json::Value,
}

impl CreateTransformRuleRequest {
    pub fn new(name: String, rule_type: String, config: serde_json::Value) -> CreateTransformRuleRequest {
        CreateTransformRuleRequest {
            name,
            rule_type,
            config,
        }
    }
}

