/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEndpointRequest {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "allowed_ips", skip_serializing_if = "Option::is_none")]
    pub allowed_ips: Option<Vec<String>>,
    #[serde(rename = "event_filter", skip_serializing_if = "Option::is_none")]
    pub event_filter: Option<Vec<String>>,
    #[serde(rename = "custom_headers", skip_serializing_if = "Option::is_none")]
    pub custom_headers: Option<serde_json::Value>,
    #[serde(rename = "retry_policy", skip_serializing_if = "Option::is_none")]
    pub retry_policy: Option<Box<models::RetryPolicy>>,
    #[serde(rename = "routing_strategy", skip_serializing_if = "Option::is_none")]
    pub routing_strategy: Option<RoutingStrategy>,
    #[serde(rename = "fallback_url", skip_serializing_if = "Option::is_none")]
    pub fallback_url: Option<String>,
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
}

impl CreateEndpointRequest {
    pub fn new(url: String) -> CreateEndpointRequest {
        CreateEndpointRequest {
            url,
            description: None,
            allowed_ips: None,
            event_filter: None,
            custom_headers: None,
            retry_policy: None,
            routing_strategy: None,
            fallback_url: None,
            format: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoutingStrategy {
    #[serde(rename = "round-robin")]
    RoundRobin,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "failover")]
    Failover,
}

impl Default for RoutingStrategy {
    fn default() -> RoutingStrategy {
        Self::RoundRobin
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "cloudevents")]
    Cloudevents,
}

impl Default for Format {
    fn default() -> Format {
        Self::Standard
    }
}

