/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateCustomDomainRequest : Register a new custom domain
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomDomainRequest {
    /// Fully qualified domain name to register
    #[serde(rename = "domain")]
    pub domain: String,
}

impl CreateCustomDomainRequest {
    /// Register a new custom domain
    pub fn new(domain: String) -> CreateCustomDomainRequest {
        CreateCustomDomainRequest {
            domain,
        }
    }
}

