/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKeyResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Full API key — only shown once
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl CreateApiKeyResponse {
    pub fn new(id: uuid::Uuid, key: String, prefix: String, message: String) -> CreateApiKeyResponse {
        CreateApiKeyResponse {
            id,
            key,
            prefix,
            message,
        }
    }
}

