/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateRoutingRuleRequest : Create a new routing rule
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoutingRuleRequest {
    #[serde(rename = "name")]
    pub name: String,
    /// Conditions that trigger this rule (e.g. event_type, header match)
    #[serde(rename = "conditions")]
    pub conditions: serde_json::Value,
    /// Optional payload transformation config
    #[serde(rename = "transform", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transform: Option<Option<serde_json::Value>>,
    #[serde(rename = "target_endpoint_id")]
    pub target_endpoint_id: uuid::Uuid,
}

impl CreateRoutingRuleRequest {
    /// Create a new routing rule
    pub fn new(name: String, conditions: serde_json::Value, target_endpoint_id: uuid::Uuid) -> CreateRoutingRuleRequest {
        CreateRoutingRuleRequest {
            name,
            conditions,
            transform: None,
            target_endpoint_id,
        }
    }
}

