/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSsoConfigRequest : Create a new SSO configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSsoConfigRequest {
    #[serde(rename = "provider")]
    pub provider: Provider,
    #[serde(rename = "domain")]
    pub domain: String,
    /// URL to SAML metadata or OIDC discovery document
    #[serde(rename = "metadata_url")]
    pub metadata_url: String,
}

impl CreateSsoConfigRequest {
    /// Create a new SSO configuration
    pub fn new(provider: Provider, domain: String, metadata_url: String) -> CreateSsoConfigRequest {
        CreateSsoConfigRequest {
            provider,
            domain,
            metadata_url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "saml")]
    Saml,
    #[serde(rename = "oidc")]
    Oidc,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Saml
    }
}

