/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Only returned on registration
    #[serde(rename = "api_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Option<String>>,
    #[serde(rename = "plan")]
    pub plan: Plan,
    #[serde(rename = "webhook_limit")]
    pub webhook_limit: i32,
    #[serde(rename = "webhook_count")]
    pub webhook_count: i32,
    #[serde(rename = "is_admin")]
    pub is_admin: bool,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CustomerResponse {
    pub fn new(id: uuid::Uuid, email: String, plan: Plan, webhook_limit: i32, webhook_count: i32, is_admin: bool, created_at: chrono::DateTime<chrono::FixedOffset>) -> CustomerResponse {
        CustomerResponse {
            id,
            email,
            name: None,
            api_key: None,
            plan,
            webhook_limit,
            webhook_count,
            is_admin,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Plan {
    #[serde(rename = "free")]
    Free,
    #[serde(rename = "pro")]
    Pro,
    #[serde(rename = "business")]
    Business,
}

impl Default for Plan {
    fn default() -> Plan {
        Self::Free
    }
}

