/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomDomain : A custom domain configured for the account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomDomain {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The custom domain (e.g. webhooks.example.com)
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "status")]
    pub status: Status,
    /// TXT record value to prove domain ownership
    #[serde(rename = "verification_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub verification_token: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CustomDomain {
    /// A custom domain configured for the account
    pub fn new(id: uuid::Uuid, domain: String, status: Status, created_at: chrono::DateTime<chrono::FixedOffset>) -> CustomDomain {
        CustomDomain {
            id,
            domain,
            status,
            verification_token: None,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verifying")]
    Verifying,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

