/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DailyDeliveryCount : Daily delivery count breakdown
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DailyDeliveryCount {
    #[serde(rename = "date")]
    pub date: chrono::NaiveDate,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "success")]
    pub success: i32,
    #[serde(rename = "failed")]
    pub failed: i32,
}

impl DailyDeliveryCount {
    /// Daily delivery count breakdown
    pub fn new(date: chrono::NaiveDate, total: i32, success: i32, failed: i32) -> DailyDeliveryCount {
        DailyDeliveryCount {
            date,
            total,
            success,
            failed,
        }
    }
}

