/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryAttempt {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "attempt_number")]
    pub attempt_number: i32,
    #[serde(rename = "status_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<Option<i32>>,
    #[serde(rename = "response_body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub response_body: Option<Option<String>>,
    #[serde(rename = "duration_ms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<Option<i32>>,
    #[serde(rename = "error_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl DeliveryAttempt {
    pub fn new(id: uuid::Uuid, attempt_number: i32, created_at: chrono::DateTime<chrono::FixedOffset>) -> DeliveryAttempt {
        DeliveryAttempt {
            id,
            attempt_number,
            status_code: None,
            response_body: None,
            duration_ms: None,
            error_message: None,
            created_at,
        }
    }
}

