/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Delivery {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "endpoint_id")]
    pub endpoint_id: uuid::Uuid,
    #[serde(rename = "event", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "attempt_count")]
    pub attempt_count: i32,
    #[serde(rename = "response_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub response_status: Option<Option<i32>>,
    #[serde(rename = "replay_count")]
    pub replay_count: i32,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Delivery {
    pub fn new(id: uuid::Uuid, endpoint_id: uuid::Uuid, status: Status, attempt_count: i32, replay_count: i32, created_at: chrono::DateTime<chrono::FixedOffset>) -> Delivery {
        Delivery {
            id,
            endpoint_id,
            event: None,
            status,
            attempt_count,
            response_status: None,
            replay_count,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

