/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployInfo {
    /// Semantic version from Cargo.toml
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Git SHA of the deployed commit
    #[serde(rename = "git_commit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub git_commit: Option<Option<String>>,
    /// ISO 8601 build timestamp
    #[serde(rename = "build_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub build_time: Option<Option<String>>,
    /// Deployment environment (production, staging, etc.)
    #[serde(rename = "environment", skip_serializing_if = "Option::is_none")]
    pub environment: Option<String>,
}

impl DeployInfo {
    pub fn new() -> DeployInfo {
        DeployInfo {
            version: None,
            git_commit: None,
            build_time: None,
            environment: None,
        }
    }
}

