/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceTokenResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl DeviceTokenResponse {
    pub fn new(id: uuid::Uuid, token: String, platform: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> DeviceTokenResponse {
        DeviceTokenResponse {
            id,
            token,
            platform,
            created_at,
        }
    }
}

