/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DomainDnsRecord : A DNS record required for domain verification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainDnsRecord {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// DNS record name/host
    #[serde(rename = "name")]
    pub name: String,
    /// DNS record value
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "status")]
    pub status: Status,
}

impl DomainDnsRecord {
    /// A DNS record required for domain verification
    pub fn new(r#type: Type, name: String, value: String, status: Status) -> DomainDnsRecord {
        DomainDnsRecord {
            r#type,
            name,
            value,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "TXT")]
    Txt,
    #[serde(rename = "CNAME")]
    Cname,
    #[serde(rename = "A")]
    A,
}

impl Default for Type {
    fn default() -> Type {
        Self::Txt
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

