/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmbedConfig : Configuration for embedded webhook dashboard
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbedConfig {
    /// CORS origins allowed to load the embed
    #[serde(rename = "allowed_origins")]
    pub allowed_origins: Vec<String>,
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<Box<models::EmbedConfigTheme>>,
    /// Enabled features (e.g. [deliveries, endpoints, playground])
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
}

impl EmbedConfig {
    /// Configuration for embedded webhook dashboard
    pub fn new(allowed_origins: Vec<String>) -> EmbedConfig {
        EmbedConfig {
            allowed_origins,
            theme: None,
            features: None,
        }
    }
}

