/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Enable2faRequest {
    #[serde(rename = "password")]
    pub password: String,
}

impl Enable2faRequest {
    pub fn new(password: String) -> Enable2faRequest {
        Enable2faRequest {
            password,
        }
    }
}

