/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Enable2faResponse : TOTP secret and QR code URL returned after enabling 2FA
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Enable2faResponse {
    /// TOTP secret key
    #[serde(rename = "secret")]
    pub secret: String,
    /// QR code provisioning URL
    #[serde(rename = "qr_url")]
    pub qr_url: String,
}

impl Enable2faResponse {
    /// TOTP secret and QR code URL returned after enabling 2FA
    pub fn new(secret: String, qr_url: String) -> Enable2faResponse {
        Enable2faResponse {
            secret,
            qr_url,
        }
    }
}

