/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EndpointHealth : Endpoint health metrics and status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointHealth {
    #[serde(rename = "endpoint_id")]
    pub endpoint_id: uuid::Uuid,
    #[serde(rename = "is_healthy")]
    pub is_healthy: bool,
    #[serde(rename = "failure_streak", skip_serializing_if = "Option::is_none")]
    pub failure_streak: Option<i32>,
    #[serde(rename = "avg_response_ms", skip_serializing_if = "Option::is_none")]
    pub avg_response_ms: Option<i32>,
    #[serde(rename = "last_failure_at", skip_serializing_if = "Option::is_none")]
    pub last_failure_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Success rate as a fraction (0.0–1.0)
    #[serde(rename = "success_rate", skip_serializing_if = "Option::is_none")]
    pub success_rate: Option<f64>,
    /// Average delivery latency in milliseconds
    #[serde(rename = "avg_latency_ms", skip_serializing_if = "Option::is_none")]
    pub avg_latency_ms: Option<f64>,
    #[serde(rename = "last_delivery_at", skip_serializing_if = "Option::is_none")]
    pub last_delivery_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "total_deliveries", skip_serializing_if = "Option::is_none")]
    pub total_deliveries: Option<i32>,
    #[serde(rename = "failed_deliveries", skip_serializing_if = "Option::is_none")]
    pub failed_deliveries: Option<i32>,
}

impl EndpointHealth {
    /// Endpoint health metrics and status
    pub fn new(endpoint_id: uuid::Uuid, is_healthy: bool) -> EndpointHealth {
        EndpointHealth {
            endpoint_id,
            is_healthy,
            failure_streak: None,
            avg_response_ms: None,
            last_failure_at: None,
            success_rate: None,
            avg_latency_ms: None,
            last_delivery_at: None,
            total_deliveries: None,
            failed_deliveries: None,
        }
    }
}

