/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endpoint {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "retry_policy")]
    pub retry_policy: Box<models::RetryPolicy>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// CIDR blocks or exact IPs
    #[serde(rename = "allowed_ips", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_ips: Option<Option<Vec<String>>>,
    /// Wildcard patterns (e.g. \"order.*\")
    #[serde(rename = "event_filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_filter: Option<Option<Vec<String>>>,
    #[serde(rename = "custom_headers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_headers: Option<Option<serde_json::Value>>,
    #[serde(rename = "routing_strategy")]
    pub routing_strategy: RoutingStrategy,
    #[serde(rename = "fallback_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fallback_url: Option<Option<String>>,
    #[serde(rename = "avg_response_ms")]
    pub avg_response_ms: i32,
    #[serde(rename = "failure_streak")]
    pub failure_streak: i32,
    #[serde(rename = "format")]
    pub format: Format,
}

impl Endpoint {
    pub fn new(id: uuid::Uuid, url: String, is_active: bool, retry_policy: models::RetryPolicy, created_at: chrono::DateTime<chrono::FixedOffset>, routing_strategy: RoutingStrategy, avg_response_ms: i32, failure_streak: i32, format: Format) -> Endpoint {
        Endpoint {
            id,
            url,
            description: None,
            is_active,
            retry_policy: Box::new(retry_policy),
            created_at,
            allowed_ips: None,
            event_filter: None,
            custom_headers: None,
            routing_strategy,
            fallback_url: None,
            avg_response_ms,
            failure_streak,
            format,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoutingStrategy {
    #[serde(rename = "round-robin")]
    RoundRobin,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "failover")]
    Failover,
}

impl Default for RoutingStrategy {
    fn default() -> RoutingStrategy {
        Self::RoundRobin
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "cloudevents")]
    Cloudevents,
}

impl Default for Format {
    fn default() -> Format {
        Self::Standard
    }
}

