/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EndpointListResponse : Paginated list of endpoints
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointListResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::Endpoint>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl EndpointListResponse {
    /// Paginated list of endpoints
    pub fn new(data: Vec<models::Endpoint>, total: i32, has_more: bool) -> EndpointListResponse {
        EndpointListResponse {
            data,
            total,
            has_more,
        }
    }
}

