/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventTypeCount : Event type occurrence count
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventTypeCount {
    #[serde(rename = "event", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event: Option<Option<String>>,
    #[serde(rename = "count")]
    pub count: i32,
}

impl EventTypeCount {
    /// Event type occurrence count
    pub fn new(count: i32) -> EventTypeCount {
        EventTypeCount {
            event: None,
            count,
        }
    }
}

