/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventType : A registered event type in the system
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventType {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Event type identifier (e.g. order.created)
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "schema_id", skip_serializing_if = "Option::is_none")]
    pub schema_id: Option<uuid::Uuid>,
}

impl EventType {
    /// A registered event type in the system
    pub fn new(id: uuid::Uuid, name: String) -> EventType {
        EventType {
            id,
            name,
            description: None,
            schema_id: None,
        }
    }
}

