/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExportDataResponse : GDPR data export containing all user data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportDataResponse {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::CustomerResponse>>,
    #[serde(rename = "endpoints", skip_serializing_if = "Option::is_none")]
    pub endpoints: Option<Vec<models::Endpoint>>,
    #[serde(rename = "deliveries", skip_serializing_if = "Option::is_none")]
    pub deliveries: Option<Vec<models::Delivery>>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<models::Team>>,
    #[serde(rename = "exported_at")]
    pub exported_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ExportDataResponse {
    /// GDPR data export containing all user data
    pub fn new(exported_at: chrono::DateTime<chrono::FixedOffset>) -> ExportDataResponse {
        ExportDataResponse {
            user: None,
            endpoints: None,
            deliveries: None,
            teams: None,
            exported_at,
        }
    }
}

