/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboundWebhookRequest : Raw webhook payload received from an external provider (Stripe, GitHub, etc.)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboundWebhookRequest {
    /// Provider name (e.g. stripe, github, shopify)
    #[serde(rename = "provider")]
    pub provider: String,
    /// Raw webhook payload body
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    /// HTTP headers from the incoming webhook request
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
}

impl InboundWebhookRequest {
    /// Raw webhook payload received from an external provider (Stripe, GitHub, etc.)
    pub fn new(provider: String, payload: serde_json::Value) -> InboundWebhookRequest {
        InboundWebhookRequest {
            provider,
            payload,
            headers: None,
        }
    }
}

