/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboundWebhookResponse : Result of processing an inbound webhook
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboundWebhookResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Processing status of the inbound webhook
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "endpoint_id")]
    pub endpoint_id: uuid::Uuid,
    #[serde(rename = "received_at")]
    pub received_at: chrono::DateTime<chrono::FixedOffset>,
}

impl InboundWebhookResponse {
    /// Result of processing an inbound webhook
    pub fn new(id: uuid::Uuid, status: Status, endpoint_id: uuid::Uuid, received_at: chrono::DateTime<chrono::FixedOffset>) -> InboundWebhookResponse {
        InboundWebhookResponse {
            id,
            status,
            endpoint_id,
            received_at,
        }
    }
}
/// Processing status of the inbound webhook
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "processing")]
    Processing,
}

impl Default for Status {
    fn default() -> Status {
        Self::Accepted
    }
}

