/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "amount_cents")]
    pub amount_cents: i64,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl InvoiceResponse {
    pub fn new(id: String, amount_cents: i64, currency: String, status: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> InvoiceResponse {
        InvoiceResponse {
            id,
            amount_cents,
            currency,
            status,
            created_at,
        }
    }
}

