/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatencyTrendResponseBucketsInner {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "avg_ms", skip_serializing_if = "Option::is_none")]
    pub avg_ms: Option<f64>,
    #[serde(rename = "p95_ms", skip_serializing_if = "Option::is_none")]
    pub p95_ms: Option<f64>,
}

impl LatencyTrendResponseBucketsInner {
    pub fn new() -> LatencyTrendResponseBucketsInner {
        LatencyTrendResponseBucketsInner {
            timestamp: None,
            avg_ms: None,
            p95_ms: None,
        }
    }
}

