/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatencyTrendResponse {
    #[serde(rename = "range")]
    pub range: String,
    #[serde(rename = "buckets")]
    pub buckets: Vec<models::LatencyTrendResponseBucketsInner>,
    #[serde(rename = "overall_avg_ms")]
    pub overall_avg_ms: f64,
}

impl LatencyTrendResponse {
    pub fn new(range: String, buckets: Vec<models::LatencyTrendResponseBucketsInner>, overall_avg_ms: f64) -> LatencyTrendResponse {
        LatencyTrendResponse {
            range,
            buckets,
            overall_avg_ms,
        }
    }
}

