/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LatencyResponse : Latency percentile breakdown for deliveries
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatencyResponse {
    /// 50th percentile (median) latency in ms
    #[serde(rename = "p50")]
    pub p50: f32,
    /// 90th percentile latency in ms
    #[serde(rename = "p90")]
    pub p90: f32,
    /// 95th percentile latency in ms
    #[serde(rename = "p95")]
    pub p95: f32,
    /// 99th percentile latency in ms
    #[serde(rename = "p99")]
    pub p99: f32,
    /// Time range of the data
    #[serde(rename = "period")]
    pub period: Period,
}

impl LatencyResponse {
    /// Latency percentile breakdown for deliveries
    pub fn new(p50: f32, p90: f32, p95: f32, p99: f32, period: Period) -> LatencyResponse {
        LatencyResponse {
            p50,
            p90,
            p95,
            p99,
            period,
        }
    }
}
/// Time range of the data
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Period {
    #[serde(rename = "24h")]
    Variant24h,
    #[serde(rename = "7d")]
    Variant7d,
    #[serde(rename = "30d")]
    Variant30d,
}

impl Default for Period {
    fn default() -> Period {
        Self::Variant24h
    }
}

