/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationListResponse {
    #[serde(rename = "notifications")]
    pub notifications: Vec<models::Notification>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "unread_count")]
    pub unread_count: i32,
}

impl NotificationListResponse {
    pub fn new(notifications: Vec<models::Notification>, total: i32, unread_count: i32) -> NotificationListResponse {
        NotificationListResponse {
            notifications,
            total,
            unread_count,
        }
    }
}

