/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthProviderListResponse : List of available OAuth providers
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthProviderListResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::OAuthProvider>,
}

impl OAuthProviderListResponse {
    /// List of available OAuth providers
    pub fn new(data: Vec<models::OAuthProvider>) -> OAuthProviderListResponse {
        OAuthProviderListResponse {
            data,
        }
    }
}

