/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthProvider : An available OAuth identity provider
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthProvider {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Provider identifier (e.g. google, github)
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "authorize_url")]
    pub authorize_url: String,
    #[serde(rename = "token_url")]
    pub token_url: String,
}

impl OAuthProvider {
    /// An available OAuth identity provider
    pub fn new(id: uuid::Uuid, name: String, client_id: String, authorize_url: String, token_url: String) -> OAuthProvider {
        OAuthProvider {
            id,
            name,
            client_id,
            authorize_url,
            token_url,
        }
    }
}

