/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthLoginRedirect : OAuth redirect information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthLoginRedirect {
    #[serde(rename = "redirect_url")]
    pub redirect_url: String,
}

impl OAuthLoginRedirect {
    /// OAuth redirect information
    pub fn new(redirect_url: String) -> OAuthLoginRedirect {
        OAuthLoginRedirect {
            redirect_url,
        }
    }
}

