/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OutboundIPsResponse : List of static outbound IP addresses for firewall whitelisting
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutboundIPsResponse {
    /// IPv4 and IPv6 addresses used for outbound requests
    #[serde(rename = "ips")]
    pub ips: Vec<String>,
}

impl OutboundIPsResponse {
    /// List of static outbound IP addresses for firewall whitelisting
    pub fn new(ips: Vec<String>) -> OutboundIPsResponse {
        OutboundIPsResponse {
            ips,
        }
    }
}

