/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedUsers {
    #[serde(rename = "users")]
    pub users: Vec<models::UserSummary>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "per_page")]
    pub per_page: i32,
}

impl PaginatedUsers {
    pub fn new(users: Vec<models::UserSummary>, total: i32, page: i32, per_page: i32) -> PaginatedUsers {
        PaginatedUsers {
            users,
            total,
            page,
            per_page,
        }
    }
}

