/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformSettings : Platform-wide configuration settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettings {
    #[serde(rename = "default_plan")]
    pub default_plan: String,
    #[serde(rename = "max_endpoints_free")]
    pub max_endpoints_free: i32,
    #[serde(rename = "max_endpoints_pro")]
    pub max_endpoints_pro: i32,
    #[serde(rename = "max_webhooks_free")]
    pub max_webhooks_free: i32,
    #[serde(rename = "max_webhooks_pro")]
    pub max_webhooks_pro: i32,
    #[serde(rename = "rate_limit_free")]
    pub rate_limit_free: i32,
    #[serde(rename = "rate_limit_pro")]
    pub rate_limit_pro: i32,
    #[serde(rename = "retry_max_attempts")]
    pub retry_max_attempts: i32,
    #[serde(rename = "retention_days_free")]
    pub retention_days_free: i32,
    #[serde(rename = "retention_days_pro")]
    pub retention_days_pro: i32,
    #[serde(rename = "maintenance_mode")]
    pub maintenance_mode: bool,
    #[serde(rename = "signup_enabled")]
    pub signup_enabled: bool,
    #[serde(rename = "plan_price_pro")]
    pub plan_price_pro: f64,
    #[serde(rename = "plan_price_business")]
    pub plan_price_business: f64,
    #[serde(rename = "resend_api_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resend_api_key: Option<Option<String>>,
    #[serde(rename = "email_sender", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_sender: Option<Option<String>>,
}

impl PlatformSettings {
    /// Platform-wide configuration settings
    pub fn new(default_plan: String, max_endpoints_free: i32, max_endpoints_pro: i32, max_webhooks_free: i32, max_webhooks_pro: i32, rate_limit_free: i32, rate_limit_pro: i32, retry_max_attempts: i32, retention_days_free: i32, retention_days_pro: i32, maintenance_mode: bool, signup_enabled: bool, plan_price_pro: f64, plan_price_business: f64) -> PlatformSettings {
        PlatformSettings {
            default_plan,
            max_endpoints_free,
            max_endpoints_pro,
            max_webhooks_free,
            max_webhooks_pro,
            rate_limit_free,
            rate_limit_pro,
            retry_max_attempts,
            retention_days_free,
            retention_days_pro,
            maintenance_mode,
            signup_enabled,
            plan_price_pro,
            plan_price_business,
            resend_api_key: None,
            email_sender: None,
        }
    }
}

