/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlaygroundTestResponse : Result of a playground test delivery
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaygroundTestResponse {
    /// HTTP status code returned by the endpoint
    #[serde(rename = "status_code")]
    pub status_code: i32,
    /// Raw response body from the endpoint
    #[serde(rename = "response_body")]
    pub response_body: String,
    #[serde(rename = "latency_ms")]
    pub latency_ms: i32,
    /// Response headers from the endpoint
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<serde_json::Value>,
}

impl PlaygroundTestResponse {
    /// Result of a playground test delivery
    pub fn new(status_code: i32, response_body: String, latency_ms: i32) -> PlaygroundTestResponse {
        PlaygroundTestResponse {
            status_code,
            response_body,
            latency_ms,
            headers: None,
        }
    }
}

