/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlaygroundTestRequest : Test a webhook payload against an endpoint in sandbox
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlaygroundTestRequest {
    #[serde(rename = "endpoint_id")]
    pub endpoint_id: uuid::Uuid,
    /// The payload to send
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    /// Custom headers to include with the request
    #[serde(rename = "headers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Option<serde_json::Value>>,
}

impl PlaygroundTestRequest {
    /// Test a webhook payload against an endpoint in sandbox
    pub fn new(endpoint_id: uuid::Uuid, payload: serde_json::Value) -> PlaygroundTestRequest {
        PlaygroundTestRequest {
            endpoint_id,
            payload,
            headers: None,
        }
    }
}

