/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PortalConfig : Customer-facing portal branding and configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortalConfig {
    #[serde(rename = "logo_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<Option<String>>,
    /// Hex color code (e.g.
    #[serde(rename = "primary_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_color: Option<Option<String>>,
    #[serde(rename = "custom_domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_domain: Option<Option<String>>,
    /// Event types to expose in the portal
    #[serde(rename = "webhook_events", skip_serializing_if = "Option::is_none")]
    pub webhook_events: Option<Vec<String>>,
}

impl PortalConfig {
    /// Customer-facing portal branding and configuration
    pub fn new() -> PortalConfig {
        PortalConfig {
            logo_url: None,
            primary_color: None,
            custom_domain: None,
            webhook_events: None,
        }
    }
}

