/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RateLimitUsage : Current rate limit usage for an endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitUsage {
    /// Current requests per second being consumed
    #[serde(rename = "current_rps")]
    pub current_rps: f64,
    /// Configured requests per second limit
    #[serde(rename = "limit_rps")]
    pub limit_rps: f64,
    /// Remaining capacity
    #[serde(rename = "remaining")]
    pub remaining: f64,
    #[serde(rename = "reset_at")]
    pub reset_at: chrono::DateTime<chrono::FixedOffset>,
}

impl RateLimitUsage {
    /// Current rate limit usage for an endpoint
    pub fn new(current_rps: f64, limit_rps: f64, remaining: f64, reset_at: chrono::DateTime<chrono::FixedOffset>) -> RateLimitUsage {
        RateLimitUsage {
            current_rps,
            limit_rps,
            remaining,
            reset_at,
        }
    }
}

