/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RateLimitConfig : Rate limiting configuration for an endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitConfig {
    /// Maximum requests per second allowed
    #[serde(rename = "requests_per_second")]
    pub requests_per_second: i32,
    /// Maximum burst above steady-state rate
    #[serde(rename = "burst_size")]
    pub burst_size: i32,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl RateLimitConfig {
    /// Rate limiting configuration for an endpoint
    pub fn new(requests_per_second: i32, burst_size: i32, enabled: bool) -> RateLimitConfig {
        RateLimitConfig {
            requests_per_second,
            burst_size,
            enabled,
        }
    }
}

