/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshTokenRequest {
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
}

impl RefreshTokenRequest {
    pub fn new(refresh_token: String) -> RefreshTokenRequest {
        RefreshTokenRequest {
            refresh_token,
        }
    }
}

