/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterSchemaRequest {
    #[serde(rename = "name")]
    pub name: String,
    /// JSON Schema document
    #[serde(rename = "schema")]
    pub schema: serde_json::Value,
}

impl RegisterSchemaRequest {
    pub fn new(name: String, schema: serde_json::Value) -> RegisterSchemaRequest {
        RegisterSchemaRequest {
            name,
            schema,
        }
    }
}

