/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReplayDeliveryResponse : Result of replaying a delivery
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplayDeliveryResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "original_id")]
    pub original_id: uuid::Uuid,
    #[serde(rename = "new_delivery_id")]
    pub new_delivery_id: uuid::Uuid,
}

impl ReplayDeliveryResponse {
    /// Result of replaying a delivery
    pub fn new(message: String, original_id: uuid::Uuid, new_delivery_id: uuid::Uuid) -> ReplayDeliveryResponse {
        ReplayDeliveryResponse {
            message,
            original_id,
            new_delivery_id,
        }
    }
}

