/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetryPolicy {
    #[serde(rename = "max_attempts")]
    pub max_attempts: i32,
    #[serde(rename = "backoff")]
    pub backoff: Backoff,
    #[serde(rename = "initial_delay_secs")]
    pub initial_delay_secs: i32,
    #[serde(rename = "max_delay_secs")]
    pub max_delay_secs: i32,
}

impl RetryPolicy {
    pub fn new(max_attempts: i32, backoff: Backoff, initial_delay_secs: i32, max_delay_secs: i32) -> RetryPolicy {
        RetryPolicy {
            max_attempts,
            backoff,
            initial_delay_secs,
            max_delay_secs,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Backoff {
    #[serde(rename = "exponential")]
    Exponential,
    #[serde(rename = "linear")]
    Linear,
    #[serde(rename = "fixed")]
    Fixed,
}

impl Default for Backoff {
    fn default() -> Backoff {
        Self::Exponential
    }
}

