/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RotateSecretResponse : New signing secret after rotation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RotateSecretResponse {
    /// New endpoint signing secret
    #[serde(rename = "secret")]
    pub secret: String,
}

impl RotateSecretResponse {
    /// New signing secret after rotation
    pub fn new(secret: String) -> RotateSecretResponse {
        RotateSecretResponse {
            secret,
        }
    }
}

