/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutingRuleListResponseDataInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "conditions")]
    pub conditions: serde_json::Value,
    #[serde(rename = "transform", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transform: Option<Option<serde_json::Value>>,
    #[serde(rename = "target_endpoint_id")]
    pub target_endpoint_id: uuid::Uuid,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl RoutingRuleListResponseDataInner {
    pub fn new(id: uuid::Uuid, name: String, conditions: serde_json::Value, target_endpoint_id: uuid::Uuid) -> RoutingRuleListResponseDataInner {
        RoutingRuleListResponseDataInner {
            id,
            name,
            conditions,
            transform: None,
            target_endpoint_id,
            enabled: None,
            created_at: None,
        }
    }
}

