/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoutingRuleListResponse : List of routing rules
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutingRuleListResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::RoutingRuleListResponseDataInner>,
}

impl RoutingRuleListResponse {
    /// List of routing rules
    pub fn new(data: Vec<models::RoutingRuleListResponseDataInner>) -> RoutingRuleListResponse {
        RoutingRuleListResponse {
            data,
        }
    }
}

