/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SchemaResponse : A registered JSON Schema for event validation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemaResponse {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version")]
    pub version: i32,
    /// The JSON Schema document
    #[serde(rename = "schema_json")]
    pub schema_json: serde_json::Value,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SchemaResponse {
    /// A registered JSON Schema for event validation
    pub fn new(id: uuid::Uuid, name: String, version: i32, schema_json: serde_json::Value, created_at: chrono::DateTime<chrono::FixedOffset>) -> SchemaResponse {
        SchemaResponse {
            id,
            name,
            version,
            schema_json,
            created_at,
        }
    }
}

