/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchResponse : Search results for webhook deliveries
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResponse {
    #[serde(rename = "deliveries")]
    pub deliveries: Vec<models::Delivery>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "per_page")]
    pub per_page: i32,
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
}

impl SearchResponse {
    /// Search results for webhook deliveries
    pub fn new(deliveries: Vec<models::Delivery>, total: i32, page: i32, per_page: i32) -> SearchResponse {
        SearchResponse {
            deliveries,
            total,
            page,
            per_page,
            has_more: None,
        }
    }
}

