/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchRequestFilters : Additional filters (status, endpoint_id, etc.)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchRequestFilters {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "endpoint_id", skip_serializing_if = "Option::is_none")]
    pub endpoint_id: Option<uuid::Uuid>,
}

impl SearchRequestFilters {
    /// Additional filters (status, endpoint_id, etc.)
    pub fn new() -> SearchRequestFilters {
        SearchRequestFilters {
            status: None,
            endpoint_id: None,
        }
    }
}

