/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimulatorResponse : Result of a simulated webhook delivery
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulatorResponse {
    #[serde(rename = "delivery_id")]
    pub delivery_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: Status,
    /// Response time from the endpoint
    #[serde(rename = "latency_ms")]
    pub latency_ms: i32,
}

impl SimulatorResponse {
    /// Result of a simulated webhook delivery
    pub fn new(delivery_id: uuid::Uuid, status: Status, latency_ms: i32) -> SimulatorResponse {
        SimulatorResponse {
            delivery_id,
            status,
            latency_ms,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "pending")]
    Pending,
}

impl Default for Status {
    fn default() -> Status {
        Self::Delivered
    }
}

