/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimulatorRequest : Send a simulated webhook event
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulatorRequest {
    #[serde(rename = "endpoint_id")]
    pub endpoint_id: uuid::Uuid,
    /// Event type to simulate (e.g. order.created)
    #[serde(rename = "event_type")]
    pub event_type: String,
    /// The webhook payload to deliver
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    /// Artificial delay before delivery (for testing timeouts)
    #[serde(rename = "delay_ms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delay_ms: Option<Option<i32>>,
}

impl SimulatorRequest {
    /// Send a simulated webhook event
    pub fn new(endpoint_id: uuid::Uuid, event_type: String, payload: serde_json::Value) -> SimulatorRequest {
        SimulatorRequest {
            endpoint_id,
            event_type,
            payload,
            delay_ms: None,
        }
    }
}

