/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SsoConfigListResponse : List of SSO configurations for the account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SsoConfigListResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::SsoConfig>,
}

impl SsoConfigListResponse {
    /// List of SSO configurations for the account
    pub fn new(data: Vec<models::SsoConfig>) -> SsoConfigListResponse {
        SsoConfigListResponse {
            data,
        }
    }
}

