/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsResponse {
    #[serde(rename = "total_deliveries")]
    pub total_deliveries: i32,
    #[serde(rename = "successful_deliveries")]
    pub successful_deliveries: i32,
    #[serde(rename = "failed_deliveries")]
    pub failed_deliveries: i32,
    #[serde(rename = "total_endpoints")]
    pub total_endpoints: i32,
    #[serde(rename = "active_endpoints")]
    pub active_endpoints: i32,
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "webhook_limit")]
    pub webhook_limit: i32,
    #[serde(rename = "webhook_count")]
    pub webhook_count: i32,
}

impl StatsResponse {
    pub fn new(total_deliveries: i32, successful_deliveries: i32, failed_deliveries: i32, total_endpoints: i32, active_endpoints: i32, plan: String, webhook_limit: i32, webhook_count: i32) -> StatsResponse {
        StatsResponse {
            total_deliveries,
            successful_deliveries,
            failed_deliveries,
            total_endpoints,
            active_endpoints,
            plan,
            webhook_limit,
            webhook_count,
        }
    }
}

