/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionResponse {
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "payment_provider")]
    pub payment_provider: String,
    #[serde(rename = "webhook_limit")]
    pub webhook_limit: i32,
    #[serde(rename = "endpoint_limit")]
    pub endpoint_limit: i32,
    #[serde(rename = "retention_days")]
    pub retention_days: i32,
    #[serde(rename = "monthly_price_cents")]
    pub monthly_price_cents: i64,
}

impl SubscriptionResponse {
    pub fn new(plan: String, status: String, payment_provider: String, webhook_limit: i32, endpoint_limit: i32, retention_days: i32, monthly_price_cents: i64) -> SubscriptionResponse {
        SubscriptionResponse {
            plan,
            status,
            payment_provider,
            webhook_limit,
            endpoint_limit,
            retention_days,
            monthly_price_cents,
        }
    }
}

