/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuccessRateResponse {
    #[serde(rename = "range")]
    pub range: String,
    #[serde(rename = "successful")]
    pub successful: i32,
    #[serde(rename = "failed")]
    pub failed: i32,
    #[serde(rename = "pending")]
    pub pending: i32,
    #[serde(rename = "success_rate")]
    pub success_rate: f64,
}

impl SuccessRateResponse {
    pub fn new(range: String, successful: i32, failed: i32, pending: i32, success_rate: f64) -> SuccessRateResponse {
        SuccessRateResponse {
            range,
            successful,
            failed,
            pending,
            success_rate,
        }
    }
}

