/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemStatusComponentsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "latency_ms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<Option<i32>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "last_checked", skip_serializing_if = "Option::is_none")]
    pub last_checked: Option<String>,
}

impl SystemStatusComponentsInner {
    pub fn new() -> SystemStatusComponentsInner {
        SystemStatusComponentsInner {
            name: None,
            status: None,
            latency_ms: None,
            description: None,
            last_checked: None,
        }
    }
}

