/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemStats {
    #[serde(rename = "total_users")]
    pub total_users: i32,
    #[serde(rename = "active_users")]
    pub active_users: i32,
    #[serde(rename = "total_endpoints")]
    pub total_endpoints: i32,
    #[serde(rename = "total_deliveries")]
    pub total_deliveries: i32,
    #[serde(rename = "plan_breakdown")]
    pub plan_breakdown: Vec<models::SystemStatsPlanBreakdownInner>,
}

impl SystemStats {
    pub fn new(total_users: i32, active_users: i32, total_endpoints: i32, total_deliveries: i32, plan_breakdown: Vec<models::SystemStatsPlanBreakdownInner>) -> SystemStats {
        SystemStats {
            total_users,
            active_users,
            total_endpoints,
            total_deliveries,
            plan_breakdown,
        }
    }
}

