/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemStatus {
    #[serde(rename = "overall_status")]
    pub overall_status: OverallStatus,
    #[serde(rename = "uptime_30d")]
    pub uptime_30d: f64,
    #[serde(rename = "components")]
    pub components: Vec<models::SystemStatusComponentsInner>,
    #[serde(rename = "checked_at")]
    pub checked_at: String,
}

impl SystemStatus {
    pub fn new(overall_status: OverallStatus, uptime_30d: f64, components: Vec<models::SystemStatusComponentsInner>, checked_at: String) -> SystemStatus {
        SystemStatus {
            overall_status,
            uptime_30d,
            components,
            checked_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OverallStatus {
    #[serde(rename = "operational")]
    Operational,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "down")]
    Down,
}

impl Default for OverallStatus {
    fn default() -> OverallStatus {
        Self::Operational
    }
}

