/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamDetailResponse {
    #[serde(rename = "team")]
    pub team: Box<models::Team>,
    #[serde(rename = "members")]
    pub members: Vec<models::TeamMember>,
    #[serde(rename = "invites")]
    pub invites: Vec<models::TeamInvite>,
}

impl TeamDetailResponse {
    pub fn new(team: models::Team, members: Vec<models::TeamMember>, invites: Vec<models::TeamInvite>) -> TeamDetailResponse {
        TeamDetailResponse {
            team: Box::new(team),
            members,
            invites,
        }
    }
}

