/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamMemberListResponse : List of members in a team
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMemberListResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::TeamMember>,
}

impl TeamMemberListResponse {
    /// List of members in a team
    pub fn new(data: Vec<models::TeamMember>) -> TeamMemberListResponse {
        TeamMemberListResponse {
            data,
        }
    }
}

