/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMember {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "joined_at")]
    pub joined_at: chrono::DateTime<chrono::FixedOffset>,
}

impl TeamMember {
    pub fn new(id: uuid::Uuid, user_id: uuid::Uuid, email: String, role: String, joined_at: chrono::DateTime<chrono::FixedOffset>) -> TeamMember {
        TeamMember {
            id,
            user_id,
            email,
            name: None,
            role,
            joined_at,
        }
    }
}

