/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestWebhookResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "status_code")]
    pub status_code: i32,
    #[serde(rename = "duration_ms")]
    pub duration_ms: i32,
    #[serde(rename = "response_body")]
    pub response_body: String,
}

impl TestWebhookResponse {
    pub fn new(success: bool, status_code: i32, duration_ms: i32, response_body: String) -> TestWebhookResponse {
        TestWebhookResponse {
            success,
            status_code,
            duration_ms,
            response_body,
        }
    }
}

