/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransformRule {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "endpoint_id")]
    pub endpoint_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "rule_type")]
    pub rule_type: String,
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl TransformRule {
    pub fn new(id: uuid::Uuid, endpoint_id: uuid::Uuid, name: String, rule_type: String, is_active: bool, created_at: chrono::DateTime<chrono::FixedOffset>) -> TransformRule {
        TransformRule {
            id,
            endpoint_id,
            name,
            rule_type,
            config: None,
            is_active,
            created_at,
        }
    }
}

