/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TwoFactorRequiredResponse {
    #[serde(rename = "requires_2fa")]
    pub requires_2fa: bool,
    #[serde(rename = "temp_token")]
    pub temp_token: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl TwoFactorRequiredResponse {
    pub fn new(requires_2fa: bool, temp_token: String, message: String) -> TwoFactorRequiredResponse {
        TwoFactorRequiredResponse {
            requires_2fa,
            temp_token,
            message,
        }
    }
}

