/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateAlertRuleRequest : Request to update an existing alert rule (all fields optional)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAlertRuleRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "condition")]
    pub condition: Condition,
    #[serde(rename = "threshold")]
    pub threshold: i32,
    #[serde(rename = "channels")]
    pub channels: Vec<Channels>,
}

impl UpdateAlertRuleRequest {
    /// Request to update an existing alert rule (all fields optional)
    pub fn new(name: String, condition: Condition, threshold: i32, channels: Vec<Channels>) -> UpdateAlertRuleRequest {
        UpdateAlertRuleRequest {
            name,
            condition,
            threshold,
            channels,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Condition {
    #[serde(rename = "failure_rate")]
    FailureRate,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "consecutive_failures")]
    ConsecutiveFailures,
}

impl Default for Condition {
    fn default() -> Condition {
        Self::FailureRate
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Channels {
    #[serde(rename = "slack")]
    Slack,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "webhook")]
    Webhook,
}

impl Default for Channels {
    fn default() -> Channels {
        Self::Slack
    }
}

