/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateEndpointRequest {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "allowed_ips")]
    pub allowed_ips: Vec<String>,
    #[serde(rename = "event_filter")]
    pub event_filter: Vec<String>,
    #[serde(rename = "custom_headers", skip_serializing_if = "Option::is_none")]
    pub custom_headers: Option<serde_json::Value>,
    #[serde(rename = "retry_policy")]
    pub retry_policy: Box<models::RetryPolicy>,
    #[serde(rename = "routing_strategy")]
    pub routing_strategy: RoutingStrategy,
    #[serde(rename = "fallback_url")]
    pub fallback_url: String,
    #[serde(rename = "format")]
    pub format: Format,
}

impl UpdateEndpointRequest {
    pub fn new(url: String, description: String, is_active: bool, allowed_ips: Vec<String>, event_filter: Vec<String>, retry_policy: models::RetryPolicy, routing_strategy: RoutingStrategy, fallback_url: String, format: Format) -> UpdateEndpointRequest {
        UpdateEndpointRequest {
            url,
            description,
            is_active,
            allowed_ips,
            event_filter,
            custom_headers: None,
            retry_policy: Box::new(retry_policy),
            routing_strategy,
            fallback_url,
            format,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoutingStrategy {
    #[serde(rename = "round-robin")]
    RoundRobin,
    #[serde(rename = "latency")]
    Latency,
    #[serde(rename = "failover")]
    Failover,
}

impl Default for RoutingStrategy {
    fn default() -> RoutingStrategy {
        Self::RoundRobin
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "cloudevents")]
    Cloudevents,
}

impl Default for Format {
    fn default() -> Format {
        Self::Standard
    }
}

