/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateRoutingRuleRequest : Update an existing routing rule (all fields optional)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRoutingRuleRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<serde_json::Value>,
    #[serde(rename = "transform", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transform: Option<Option<serde_json::Value>>,
}

impl UpdateRoutingRuleRequest {
    /// Update an existing routing rule (all fields optional)
    pub fn new(name: String) -> UpdateRoutingRuleRequest {
        UpdateRoutingRuleRequest {
            name,
            conditions: None,
            transform: None,
        }
    }
}

