/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateSsoConfigRequest : Update an SSO configuration (all fields optional)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSsoConfigRequest {
    #[serde(rename = "provider")]
    pub provider: Provider,
    #[serde(rename = "domain")]
    pub domain: String,
}

impl UpdateSsoConfigRequest {
    /// Update an SSO configuration (all fields optional)
    pub fn new(provider: Provider, domain: String) -> UpdateSsoConfigRequest {
        UpdateSsoConfigRequest {
            provider,
            domain,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "saml")]
    Saml,
    #[serde(rename = "oidc")]
    Oidc,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Saml
    }
}

