/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateTransformRuleRequest : Update an existing transform rule (all fields optional)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTransformRuleRequest {
    #[serde(rename = "name")]
    pub name: String,
    /// Updated transformation configuration
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
}

impl UpdateTransformRuleRequest {
    /// Update an existing transform rule (all fields optional)
    pub fn new(name: String) -> UpdateTransformRuleRequest {
        UpdateTransformRuleRequest {
            name,
            config: None,
        }
    }
}

