/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateSubscriptionRequest : Request to change subscription plan
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSubscriptionRequest {
    /// Target plan name
    #[serde(rename = "plan")]
    pub plan: Plan,
    /// Whether to prorate charges for the current billing period
    #[serde(rename = "proration", skip_serializing_if = "Option::is_none")]
    pub proration: Option<bool>,
}

impl UpdateSubscriptionRequest {
    /// Request to change subscription plan
    pub fn new(plan: Plan) -> UpdateSubscriptionRequest {
        UpdateSubscriptionRequest {
            plan,
            proration: None,
        }
    }
}
/// Target plan name
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Plan {
    #[serde(rename = "free")]
    Free,
    #[serde(rename = "pro")]
    Pro,
    #[serde(rename = "business")]
    Business,
}

impl Default for Plan {
    fn default() -> Plan {
        Self::Free
    }
}

