/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpgradeResponse {
    #[serde(rename = "checkout_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub checkout_url: Option<Option<String>>,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl UpgradeResponse {
    pub fn new(provider: String, message: String) -> UpgradeResponse {
        UpgradeResponse {
            checkout_url: None,
            provider,
            message,
        }
    }
}

