/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpgradeRequest {
    #[serde(rename = "plan")]
    pub plan: Plan,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Provider>,
}

impl UpgradeRequest {
    pub fn new(plan: Plan) -> UpgradeRequest {
        UpgradeRequest {
            plan,
            provider: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Plan {
    #[serde(rename = "pro")]
    Pro,
    #[serde(rename = "business")]
    Business,
}

impl Default for Plan {
    fn default() -> Plan {
        Self::Pro
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "stripe")]
    Stripe,
    #[serde(rename = "polar")]
    Polar,
    #[serde(rename = "iyzico")]
    Iyzico,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Stripe
    }
}

