/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UsageStatsResponse : Account usage statistics summary
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageStatsResponse {
    /// Number of active endpoints
    #[serde(rename = "endpoints_count")]
    pub endpoints_count: i32,
    /// Total deliveries in current period
    #[serde(rename = "deliveries_count")]
    pub deliveries_count: i32,
    /// Number of teams
    #[serde(rename = "teams_count")]
    pub teams_count: i32,
    /// Storage used in bytes
    #[serde(rename = "storage_used_bytes")]
    pub storage_used_bytes: i32,
}

impl UsageStatsResponse {
    /// Account usage statistics summary
    pub fn new(endpoints_count: i32, deliveries_count: i32, teams_count: i32, storage_used_bytes: i32) -> UsageStatsResponse {
        UsageStatsResponse {
            endpoints_count,
            deliveries_count,
            teams_count,
            storage_used_bytes,
        }
    }
}

