/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAnalytics : User analytics data for admin view
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAnalytics {
    #[serde(rename = "daily_deliveries")]
    pub daily_deliveries: Vec<models::DailyDeliveryCount>,
    #[serde(rename = "top_events")]
    pub top_events: Vec<models::EventTypeCount>,
    #[serde(rename = "endpoint_health")]
    pub endpoint_health: Vec<models::EndpointHealth>,
}

impl UserAnalytics {
    /// User analytics data for admin view
    pub fn new(daily_deliveries: Vec<models::DailyDeliveryCount>, top_events: Vec<models::EventTypeCount>, endpoint_health: Vec<models::EndpointHealth>) -> UserAnalytics {
        UserAnalytics {
            daily_deliveries,
            top_events,
            endpoint_health,
        }
    }
}

