/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidateEventResponse : Result of validating an event payload against a schema
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateEventResponse {
    #[serde(rename = "valid")]
    pub valid: bool,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::ValidateEventResponseErrorsInner>>,
}

impl ValidateEventResponse {
    /// Result of validating an event payload against a schema
    pub fn new(valid: bool) -> ValidateEventResponse {
        ValidateEventResponse {
            valid,
            errors: None,
        }
    }
}

