/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerifyCustomDomainResponse : Result of domain verification attempt
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyCustomDomainResponse {
    #[serde(rename = "status")]
    pub status: Status,
    /// DNS records that need to be configured
    #[serde(rename = "dns_records")]
    pub dns_records: Vec<models::DomainDnsRecord>,
}

impl VerifyCustomDomainResponse {
    /// Result of domain verification attempt
    pub fn new(status: Status, dns_records: Vec<models::DomainDnsRecord>) -> VerifyCustomDomainResponse {
        VerifyCustomDomainResponse {
            status,
            dns_records,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Verified
    }
}

