/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookTemplate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "payload_template", skip_serializing_if = "Option::is_none")]
    pub payload_template: Option<serde_json::Value>,
}

impl WebhookTemplate {
    pub fn new(id: String, name: String, description: String, category: String) -> WebhookTemplate {
        WebhookTemplate {
            id,
            name,
            description,
            category,
            payload_template: None,
        }
    }
}

